Server:
  Port: 8888
  IP: 0.0.0.0

DBConf:
  DbName: "pipe_identify"
  Path: localhost:3306
  Username: root
  Password: "your_password"
  Param: "charset=utf8mb4&parseTime=True&loc=Local"

Auth:
  Seconds: 604800
  Secret: "your_jwt_secret_key_123456"
  IgnorePath:
    - /api/auth/login
    - /api/auth/register
    - /api/ping

Log:
  Mode: "default"
  Path: "./logs"
